//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Car_Id { get; set; }
        public string Car_Initial { get; set; }
        public string Car_Number { get; set; }
        public string Car_Type { get; set; }
        public string Car_Length { get; set; }
        public string Car_Status { get; set; }
    
        public virtual UnitCar UnitCar { get; set; }
    }
}
