//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class cycle31_dbEntities1 : DbContext
    {
        public cycle31_dbEntities1()
            : base("name=cycle31_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<EmployeeInfo> EmployeeInfoes { get; set; }
        public virtual DbSet<json> jsons { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<UnitCar> UnitCars { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserYard> UserYards { get; set; }
        public virtual DbSet<Yard> Yards { get; set; }
        public virtual DbSet<GetUnitsView> GetUnitsViews { get; set; }
    
        public virtual ObjectResult<getunits_Result> getunits()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getunits_Result>("getunits");
        }
    }
}
