//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetUnitsView
    {
        public int yard_id { get; set; }
        public string yard_name { get; set; }
        public string yard_location { get; set; }
        public int track_id { get; set; }
        public string track_name { get; set; }
        public string track_length { get; set; }
        public int unit_id { get; set; }
        public string unit_name { get; set; }
        public int car_id { get; set; }
        public string car_initial { get; set; }
        public string car_number { get; set; }
        public string car_type { get; set; }
        public string car_length { get; set; }
        public string car_status { get; set; }
    }
}
