//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.Units = new HashSet<Unit>();
        }
    
        public int Track_Id { get; set; }
        public string Track_Name { get; set; }
        public string Track_Length { get; set; }
        public int Yard_Id { get; set; }
    
        public virtual Yard Yard { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
    }
}
