//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.UnitCars = new HashSet<UnitCar>();
        }
    
        public int Unit_Id { get; set; }
        public string Unit_Name { get; set; }
        public int Track_Id { get; set; }
    
        public virtual Track Track { get; set; }
        public virtual ICollection<UnitCar> UnitCars { get; set; }
    }
}
