//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yard
    {
        public Yard()
        {
            this.Tracks = new HashSet<Track>();
        }
    
        public int Yard_Id { get; set; }
        public string Yard_Name { get; set; }
        public string Yard_Location { get; set; }
    
        public virtual ICollection<Track> Tracks { get; set; }
    }
}
